version: '3.7'

services:

  influxdb:
    image: influxdb:2.7.5
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=${DOCKER_INFLUXDB_INIT_RETENTION}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      
  telegraf:
    image: telegraf:1.29.4-alpine
    container_name: telegraf
    restart: always
    environment:
      - OPCUA_ENDPOINT_URL=${OPC_UA_SERVER}
      - KAFKA_BROKER_SERVER=${KAFKA_BROKER_SERVER}
      - INFLUX_SERVER=${INFLUX_SERVER}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - INFLUX_ORGANIZATION=${INFLUX_ORGANIZATION}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
    depends_on:
      - influxdb
    volumes:
      - ./config/opcua_listener.toml:/etc/telegraf/telegraf.conf:ro
